### ISSUE TITLE
MongoDB should be set in .env.example

### ISSUE THREAD

**Issue by lee-40square** [reviewninja/vagrant.review.ninja#5]
Currently the variable is empty in .env.example but the ReadMe indicates that the default is fine. So either the documentation should have a step to set `export MONGODB=` or it should have a default setting of `127.0.0.1:27017`.

**Comment by flower-pot** [comment]
i think `127.0.0.1:27017` as default should be fine, what do you think @fabianschwarzfritz @dtornow @dfarr

**Comment by dfarr** [comment]
:+1: will update

**Comment by dfarr** [comment]
[Done!](https://github.com/reviewninja/review.ninja/blob/master/.env.example#L4)
